### ISSUE TITLE
Shortcuts are inactive on disabled button in Firefox 

### ISSUE THREAD

**Issue by fidlip** [omridevk/ng-keyboard-shortcuts#97] opened 2020-11-05 00:39 UTC
When I click button, and disable it immediately, keyboard shortcuts become nonfunctional in **Firefox**. It behave as expected in Chrome.

I prepared sample application in sandbox from your official example:

https://codesandbox.io/s/ng-keyboard-shortcuts-example-forked-6ow1k

**Comment by omridevk** [comment] 2020-11-05 11:16
thank you for  reporting  the issue, I will look into it and will update the issue accordingly.

**Comment by omridevk** [comment] 2020-11-05 11:17
I assume it is related to the fact that the button is disabled but is focused after clicked.

**Comment by fidlip** [comment] 2020-11-05 11:32
Yes it very probably is.

**Comment by omridevk** [comment] 2021-06-13 13:34
Duplicate of #

**Comment by omridevk** [comment] 2021-06-13 13:35
5``

**Closed as completed by omridevk** 2021-06-13 13:34 UTC
Labels: bug
