### ISSUE TITLE
[closeKey]="'escape'" seems to be broken in 7.1.2

### ISSUE THREAD

**Issue by jnfaerch** [omridevk/ng-keyboard-shortcuts#29] opened 2019-05-28 06:19 UTC
**Describe the bug** (minor problem ;)
`[closeKey]="'escape'"` does not work on `<ng-keyboard-shortcuts-help [key]="'?'" [closeKey]="'escape'"></ng-keyboard-shortcuts-help>`

**To Reproduce**
1. Insert `[closeKey]="'escape'"` in your help element
2. Open the keyboard shortcuts modal
3. Click the `escape` key

**Expected behavior**
The modal is supposed to close on `escape` press

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser Chrome, Firefox
 - Version, latest

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
This is a minor detail as clicking the help key (`?` in this case) again or clicking the backdrop works like a charm

And thanks for the lightning fast upgrade to 7.1.2 👍

**Comment by omridevk** [comment] 2019-05-28 08:39
@jnfaerch 
Thanks for reporting yet another issue :) I really appreciate it :) 

Is this a regression or is this feature never worked for since the first time I added it? I suspect this may have been an effect of the new Sequence feature. 
Will look into it and hopefully release a quick fix as soon as possible. 

My next features on the roadmap are:
1. Adding tests (which should eliminate a lot of similar bugs like these)
2. Adding support for multiple shortcut having bound to the same key combination or sequence.

**Comment by jnfaerch** [comment] 2019-05-28 09:08
Sorry forgot to note it. I don't really remember but since I already had `[closeKey]="'escape'"` in my code I guess(!) it's a regression. Not a big deal though ;)

**Comment by omridevk** [comment] 2019-05-28 11:44
@jnfaerch 
As a workaround for now, you can use ```[closeKey]```="'esc'"
I will release a version today to address this, that it will support the same syntax as previously, i.e "esc" and "escape", in the meantime, you can use "esc" instead.

**Comment by jnfaerch** [comment] 2019-05-28 11:59
`[closeKey]="'esc'"` works perfectly. Thx 👍

**Comment by jnfaerch** [comment] 2019-05-28 12:04
Off topic: Cannot figure out if you're trying to be sarcastic in your pay off but grammatically speaking it should be `If it's worth doing, it's worth doing well.` (with the extra `'t`) 😉

**Comment by omridevk** [comment] 2019-05-28 12:26
@jnfaerch I actually didn't notice the grammar mistake there until you mentioned it now, wrote it in a hurry I guess :P

**Comment by omridevk** [comment] 2019-05-28 14:29
should be fixed now in:
https://github.com/omridevk/ng-keyboard-shortcuts/releases/tag/7.1.3

**Closed as completed by omridevk** 2019-05-28 14:29 UTC
