### ISSUE TITLE
ShortcutInput "target" trigger the command even if the target element is NOT in focus

### ISSUE THREAD

**Issue by amr-alamir** [omridevk/ng-keyboard-shortcuts#50] opened 2020-01-15 20:15 UTC
I can't get the `target` prop of `ShortcutInput` interface to limit command triggering only when the target is in focus.

I created [this stackblitz](https://stackblitz.com/edit/ng-keyboard-shortcuts-target) in which a value is supposed to change with up and down arrow only if input has focus

here is a code snippet
```typescript
{
    key: "down",
    preventDefault: true,
    command: () => --this.val,
    target: this.input.nativeElement,
}
```

In either case ( input focused or not ) value is still changing.

what am I doing wrong? or is this a bug?

**Comment by omridevk** [comment] 2020-01-15 21:11
It seems like a regression, i'll have look into it, will update tomorrow.
Thanks for reporting the issue.

**Comment by omridevk** [comment] 2020-01-15 21:12
And thanks for the stackblitz which made it a lot easier to see the issue.

**Comment by omridevk** [comment] 2020-01-15 21:15
Yes, this indeed seems like a regression bug, i'll fix it ASAP. thanks a lot for reporting the issue (this issue only happens when using sequences, and since one key counts as sequence (at least as far as the code goes). 
Sorry for the inconvenience.

**Comment by omridevk** [comment] 2020-01-15 21:18
k, found the root cause of the issue:
https://github.com/omridevk/ng-keyboard-shortcuts/blob/master/projects/ng-keyboard-shortcuts/src/lib/ng-keyboard-shortcuts.service.ts#L155-L157
seems like I have not implemented the same behavior in the sequences code.
Will have a new version released tomorrow. thanks for the patience and again thanks for catching the issue. 
Hopefully my tests (going to add some) will catch these kind of regressions in the future.

**Comment by amr-alamir** [comment] 2020-01-15 22:50
Thank you for the quick response and for all these efforts that make our life easier ☺.

**Comment by omridevk** [comment] 2020-01-16 15:22
@amr-alamir 
Fixed in version:
https://github.com/omridevk/ng-keyboard-shortcuts/releases/tag/8.2.5

Please feel free to update via NPM.
And please let me know if the issue persist.

**Comment by omridevk** [comment] 2020-01-16 15:22
Closing, please re-open if issue persist.

**Closed as completed by omridevk** 2020-01-16 15:22 UTC
Labels: bug

**Comment by amr-alamir** [comment] 2020-01-17 14:16
Thank you for the fix, and here is the [working stackblitz](https://stackblitz.com/edit/ng-keyboard-shortcuts-target-fixed)

**Comment by omridevk** [comment] 2020-01-17 17:55
I'll update the documentation example to include such use use cass

**Comment by alexmercerind** [comment] 2025-07-01 06:56
When I remove the target entirely, it no longer works.
