### ISSUE TITLE
Compilation problem: ng-keyboard-shortcuts.plugin is missing

### ISSUE THREAD

**Issue by ssj4maiko** [omridevk/ng-keyboard-shortcuts#137] opened 2022-05-23 17:27 UTC
I recently added your library to my project, and I got the following error during compilation.

```
Error: node_modules/ng-keyboard-shortcuts/index.d.ts:5:49 - error TS2307: Cannot find module './lib/ng-keyboard-shortcuts.plugin' or its corresponding type declarations.

5 export { KeyboardShortcutsPluginProvider } from "./lib/ng-keyboard-shortcuts.plugin";

```

Version 3.0.6

Commenting the line makes it work, but of course, it should cause problems for new users, besides, I'm guessing there must be some special functionality that may be missed with that, but well, there is still a problem nonetheless.

I'm using Angular 13, and again, just commenting that makes it work, so it's not hard for me to fix for myself, so no haste I guess. Of course, no problems in functionality and it works wonderfully.

Edit:
There is also this error
```
ERROR TypeError: can't access property "currentValue", changes.closeKey is undefined
    ngOnChanges ng-keyboard-shortcuts.mjs:1338
```
The file is this: `ng-keyboard-shortcuts/fesm2020/ng-keyboard-shortcuts.mjs`

Adding this just before course also fixes the problem:
`if (!changes["closeKey"]) { return; }`

**Comment by Radoslaw-Domanski** [comment] 2022-06-07 18:32
Just updated this lib to latest version with angular 14. Same problem.

**Comment by marcelolara** [comment] 2022-06-23 20:39
Same problem here with version 13.0.6 and angular 13

**Comment by kishoresahas** [comment] 2022-06-24 10:20
Getting it all versions after 13.0.5

**Comment by omridevk** [comment] 2022-07-13 11:18
I'll look into it, sorry for the delay.

**Comment by omridevk** [comment] 2022-07-13 11:35
Can you please provide a link to reproduce? I cannot reproduce it in my local playground env nor in codesandbox.
Thanks.

**Comment by omridevk** [comment] 2022-07-13 14:12
Should be fixed now in 13.0.7 please let me know if the issue persist.

**Comment by omridevk** [comment] 2022-07-17 16:43
Is it solved?

**Comment by Washipp** [comment] 2022-08-15 08:57
13.0.7 solved it for me using angular 13

**Comment by omridevk** [comment] 2022-08-15 09:50
Closing, let me know if the issue persist, I will look again.

**Closed as completed by omridevk** 2022-08-15 09:50 UTC
