### ISSUE TITLE
Prevent Default Space Key in FireFox 

### ISSUE THREAD

**Issue by 838** [omridevk/ng-keyboard-shortcuts#35] opened 2019-07-04 10:04 UTC
**Describe the bug**
preventDefault on space key is not respected in FireFox

**To Reproduce**
1. Create a button with click event
```
// .html
<button (click)="doStuff()"></button>

// .ts

public doStuff() {
   console.log('Button clicked');
}
```
2. Generate a shortcut 
```
{
        key: 'space',
        label: 'label',
        description: 'play/pause',
        preventDefault: true,
        command: () => console.log('shortcut space'),
},
```
3. Open inspect element

4. Make sure button has keyboard focus

5. Press space key on keyboard  

6. Both click event and shortcut event are triggered. 

![Screen Shot 2019-07-04 at 11 43 05 AM](https://user-images.githubusercontent.com/3314171/60657040-e949a200-9e50-11e9-817b-65f0173a7275.png)

**Expected behavior**
The click event should be prevented

**Desktop (please complete the following information):**
 - OS: macOS - 10.14.5
 - Browser Firefox - 67.0.4 (64-bit)

**Additional context**
I believe the issue is happening because FF triggers click event on 'keyup' when space key is released.

**Comment by omridevk** [comment] 2019-08-03 18:02
I will look into it very soon, sorry for the delay guys.

**Comment by omridevk** [comment] 2020-03-25 22:15
re-opening this, as I will revert the PR as it seems to be a bug in Firefox itself and caused regression in this library in other browsers:
https://bugzilla.mozilla.org/show_bug.cgi?id=1487102
I'll keep track of the firefox, but hopefully they will resolve it soon, so the keydown event prevent default won't trigger mouse click event.

**Comment by omridevk** [comment] 2020-07-22 00:17
closing, known limitation.

**Closed as completed by omridevk** 2020-07-22 00:17 UTC
Labels: bug
