### ISSUE TITLE
cmd + b Not Working

### ISSUE THREAD

**Issue by sidikhanrei** [omridevk/ng-keyboard-shortcuts#19] opened 2019-05-17 19:39 UTC
I was try this plugins and work for some combinations.
But when I tried **cmd / ctrl + b** is not working

**Comment by omridevk** [comment] 2019-05-18 00:55
see working example here:
https://codesandbox.io/s/ngkeyboardshortcuts-example-t8h4j

**Comment by omridevk** [comment] 2019-05-18 00:57
Please provide a codesandbox example demonstrating the issue as I cannot reproduce.
And Thanks for reporting it in the first place :)

**Comment by omridevk** [comment] 2019-05-18 00:57
Feel free to re-open if issue persist.

**Comment by sidikhanrei** [comment] 2019-05-18 01:16
Please have a look at console.
No feedback for command: e => console.log(e),

it is not responding to ctrl + b

![image](https://user-images.githubusercontent.com/10180529/57962753-480c9800-7945-11e9-8002-2ce40e5e8ab8.png)

**Comment by omridevk** [comment] 2019-05-18 10:12
Which operating system are you using? Thanks

**Comment by sidikhanrei** [comment] 2019-05-18 14:55
> Which operating system are you using? Thanks

I am using Win 10

**Comment by omridevk** [comment] 2019-05-18 14:57
@sidikhanrei 
Sorry, should have asked all of these questions in the first place:
Desktop (please complete the following information):

OS: Windows 10
Browser [e.g. chrome, safari]
Version [e.g. 22]

Thanks, sorry for the back and forth on this.

**Comment by sidikhanrei** [comment] 2019-05-18 15:11
@omridevk 

OS: Windows 10
Browser: Chrome
Version: 74.0.3729.157 (Official Build) (64-bit)

I've tested on Firefox and its not working too.

Thank you for your response

**Comment by sidikhanrei** [comment] 2019-05-18 15:15
This is my code,

- ctrl + i = work
- ctrl + s = work
- ctrl + e = work
- ctrl + b = not working

```
this.shortcuts.push(
            {
                key: ["cmd + b"],
                allowIn: [AllowIn.Textarea, AllowIn.Input],
                command: e => console.log(e),
                preventDefault: true
            },
            {
                key: ["cmd + i"],
                allowIn: [AllowIn.Textarea, AllowIn.Input],
                command: e => {
                    this.FormatText('i');
                },
                preventDefault: true
            },
            {
                key: ["cmd + s"],
                allowIn: [AllowIn.Textarea, AllowIn.Input],
                command: e => {
                    this.FormatText('s');
                },
                preventDefault: true
            },
            {
                key: ["cmd + e"],
                allowIn: [AllowIn.Textarea, AllowIn.Input],
                command: e => {
                    if (this.EmojiShown && this.EmojiCanHide) {
                        this.HideEmoji();
                    }else{
                        this.ShowEmoji();
                    }
                },
                preventDefault: true
            }
        );
```

**Comment by omridevk** [comment] 2019-05-18 15:29
@sidikhanrei 
I am having hard time reproducing the issue, when I go to the following sandbox:
https://codesandbox.io/s/ngkeyboardshortcuts-example-iv7ow
I do see output in the console.
tested both in Windows 10 with Chrome Version 74.0.3729.157 (Official Build) (64-bit) and Firefox.
Also tested in Mac with Chrome and Firefox, and seems to be working as expected. 

Can you please the enter following gitter channel I created:
https://gitter.im/ng-keyboard-shortcuts/community#
I would like to further investigate the issue with you if you don't mind.

**Comment by sidikhanrei** [comment] 2019-05-18 15:31
It would be my pleasure

**Comment by omridevk** [comment] 2019-05-18 15:50
Closing the issue. The issue was resolved in the gitter thread:
https://gitter.im/ng-keyboard-shortcuts/community#
Basically, a collision between electron key binding and angular. 
Thanks @sidikhanrei for reporting and helping resolving the issue.

**Comment by sidikhanrei** [comment] 2019-05-18 15:50
It's perfectly working now.

Thank you so much @omridevk 
it's not issue with your plugins.
Your plugins seem overided by some code of my electron.

Its fix now
and work like a charm

**Closed as completed by omridevk** 2019-05-18 15:50 UTC
